AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for kittens carousel static website deploy on s3 through
  cloudfront and route 53
Parameters:
  HostedZoneName:
    Description: DNS Name of existing Amazon Route 53 hosted zone
    Type: AWS::Route53::HostedZone::Id

  KittensSubDomain:
    Description: Full domain name for the App.
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref KittensSubDomain #www.clarusway.us
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      WebsiteConfiguration:
        IndexDocument: index.html

  KittensBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket # Required
      PolicyDocument: # Required
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: "*"
            Sid: PublicReadGetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'MyBucket', /*]]

  MyCloudfront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref KittensSubDomain
        Comment: Cloudfront Distribution pointing to Kittens S3 bucket
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          TargetOriginId: KittensOrigin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt MyBucket.WebsiteURL]]
            Id: KittensOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:844750738681:certificate/ #enter certificate here
          SslSupportMethod: sni-only

  MyRecordName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneName
      RecordSets:
        - Name: !Ref KittensSubDomain
          Type: A
          AliasTarget:
            DNSName: !GetAtt MyCloudfront.DomainName
            HostedZoneId: #enter hostedzoneid

Outputs:
  BucketName:
    Description: S3 Bucket URL for Kittens Website
    Value: !GetAtt MyBucket.WebsiteURL
  CloudfrontEndpoint:
    Description: Endpoint for Kittens Cloudfront
    Value: !GetAtt MyCloudfront.DomainName
  FullDomainName:
    Description: Full Domain Name of my Application
    Value: !Ref KittensSubDomain
